### ISSUE TITLE
Dataloader should pull MNIST Data from github LFS

### ISSUE THREAD

**Issue by mgkwill** [lava-nc/lava#10]
Implement dataloader that can pull data from Github LFS link.

https://github.com/lava-nc/lava/blob/9d80ea15af495b87df7f4b63e83531bdaf7d41f9/lava/utils/dataloader/mnist.py#L31-L36

Or update instructions to use git lfs.
```
git lfs install
git lfs pull
```

**Comment by awintel** [comment]
@srrisbud, @mgkwill, @bamsumit Did this get resolved as we discussed offline?

**Comment by srrisbud** [comment]
It is resolved for MNIST. git clone downloads correct NPY files from LFS. But in general, for other examples/apps/datasets, we will not host any data natively in the repos themselves.
