### ISSUE TITLE
ProcessModel Tags: Multiple tag matching in model selection in the RunConfig is not supported

### ISSUE THREAD

**Issue by srrisbud** [lava-nc/lava#115]
Currently, in Loihi1SimCfg, we only check if 1 tag matches in the tag-list of a ProcessModel to select it. We need to enhance this to match multiple tags. For example, user may want to select a model with tags "bit_accurate" AND "slow" simultaneously.

**Comment by awintel** [comment]
We need to revisit the whole RunConfig.select() mechanism. The current "general" RunConfig does not really work for all conceivable cases but too much to do before this next release.

The first step is to list all possible cases and then decide what to do in each.

We also likely need the ability to specify which set of processes a certain tag gets applied to.

Perhaps the defaults should be that we "can" set ProcModels for each class or specific instance of a Process. Of course you do not want to do this in general.
