### ISSUE TITLE
[FYI] Lava on conda-forge

### ISSUE THREAD

**Issue by Tobias-Fischer** [lava-nc/lava#119]
Dear Lava developers,

You might have heard of conda, the package manager and virtual environment tool. It is becoming increasingly popular to install a variety of software. conda-forge is the community driven collection of recipes (which result in packages).

This is not an issue, but instead to let you know that I created recipes for lava (see e.g. https://github.com/conda-forge/lava-feedstock/blob/master/recipe/meta.yaml for an example of such a recipe), lava-optimization and lava-dl. These can now be easily installed via `conda install lava lava-optimization lava-dl -c conda-forge`. 

If you want, I can create a PR to add conda-forge as additional means of installation - many people love it, as it's very easy to install many packages without having to worry about version conflicts (which often happen with pip).

If one of the lava developers want to become a maintainer of these recipes, please let me know, I'd be more than happy to add you.

Feel free to close, as I said it's not really an issue.

**Comment by Tobias-Fischer** [comment]
Should also mention that this would make 3rd party integration much much easier :)

**Comment by mgkwill** [comment]
Hi @Tobias-Fischer thanks for this issue and for adding a recipe in conda-forge!

I use conda at times and I think it would be nice to have install instructions for conda.

Also did you see our recent releases? lava-dnf is out and we've bumped versions. 

I saw the python version as 3.6 or higher. I'd be surprised if less than 3.8 worked.

**Comment by mgkwill** [comment]
> If one of the lava developers want to become a maintainer of these recipes, please let me know, I'd be more than happy to add you.

I'll get back to you on this.

**Comment by Tobias-Fischer** [comment]
Hiya,

Yes, conda-forge has bots that automatically pick up new versions - I already merged them in :).

Which features of Python 3.8 do you make use of? I can change the recipe to enforce 3.8 and higher .. easy enough.

**Comment by mgkwill** [comment]
> Which features of Python 3.8 do you make use of? I can change the recipe to enforce 3.8 and higher .. easy enough.

I'm not sure off the top of my head, I'll run our unit tests on 3.6. But we had at least one person say they couldn't get it to work on 3.7.

**Comment by mgkwill** [comment]
For documentation purposes these are the conda-forge recipes for lava-nc:
https://github.com/conda-forge/lava-feedstock/blob/master/recipe/meta.yaml (FYI @joyeshmishra)
https://github.com/conda-forge/lava-dl-feedstock/blob/master/recipe/meta.yaml (FYI @bamsumit)
https://github.com/conda-forge/lava-dnf-feedstock/blob/master/recipe/meta.yaml (FYI @mathisrichter)
https://github.com/conda-forge/lava-optimization-feedstock/blob/master/recipe/meta.yaml (FYI @GaboFGuerra)

Install all of the above:
`conda install lava lava-dl lava-dnf lava-optimization -c conda-forge`
or individually (lava-dl for example):
`conda install lava-dl -c conda-forge`

I installed the above using conda and the install worked for me. Thanks again @Tobias-Fischer

**Comment by Tobias-Fischer** [comment]
Nice! Is there a way to run the unit tests without pybuilder? Running them in the conda-forge feedstocks would be ideal, at the moment I just test whether I can import some of the libraries.

**Comment by mgkwill** [comment]
> Nice! Is there a way to run the unit tests without pybuilder? Running them in the conda-forge feedstocks would be ideal, at the moment I just test whether I can import some of the libraries.

You should be able to run the unit tests using `python -m unittest` from top level DIR after some namespace refactoring done by @bamsumit

**Comment by Tobias-Fischer** [comment]
Cool - added the unit tests here (and already found a bug as `scipy` wasn't listed as dependency): https://github.com/conda-forge/lava-feedstock/pull/5

**Comment by mgkwill** [comment]
Hi @Tobias-Fischer - FYI we updated versions.

I'm going to close this as done since you have it in conda-forge already. 

Thanks again for doing this!

**Comment by Tobias-Fischer** [comment]
Thanks - the conda-forge bot already triggered the version update :).

Do you want me to send a PR to add conda as an additional means of installation?

**Comment by mgkwill** [comment]
That would be great! :)
