### ISSUE TITLE
Process run not shown in Jupyter

### ISSUE THREAD

**Issue by Tobias-Fischer** [lava-nc/lava#120]
Just following Andreas' tutorial and saw that he needed to pull up the terminal window to show the output of the running Process.

We have had similar problems with ROS, see https://github.com/RoboStack/jupyter-ros for some inspiration on how this could be solved.

I realise it's probably not high priority but thought it's worth opening an issue anyhow.

**Comment by awintel** [comment]
Cool. Thanks for pointing this out.

**Comment by PhilippPlank** [comment]
@mgkwill Is this issue solved with our current logger solution?
