### ISSUE TITLE
CProcessModel: enable process logic in C

### ISSUE THREAD

**Issue by jlakness-intel** [lava-nc/lava#13]
Requirements:
[ ] Compile a C program from a specified source in the python object
[ ] Load a C function into a python object
[ ] simple C API for channel communication (send, recv, peek, probe)
[ ] Share state (numpy data and protocol signals) with the python object

Possibilities:
1. Separate C process compiled and launched by python
2. CFFI call to a run function in a separate thread
3. Python extension implemented as a module and class object

Starting definition:
https://github.com/lava-nc/lava/blob/9d80ea15af495b87df7f4b63e83531bdaf7d41f9/lava/magma/core/model/c/model.py#L8

**Comment by jlakness-intel** [comment]
### Issue update:
Some offline discussions have refined this feature request.

### Long-term Objective: 
The ability to write a C run function once, which Lava will modify and compile to run on any of the target platforms.
- Targets in order of development priority
   1. Python Superhost
   2. Loihi Embedded
   3. Loihi host
   4. C++ superhost
- Interface
   - user defines run function (called with state)
   - user can call port functions (send, recv, peek, probe)

### Implementation idea
The C API will be defined as a header file which is interpreted differently on different platforms. The python superhost implementation will use a PyObjectModel for most of the compiler and runtime interface. The C code will interact with the port objects and call the port API functions directly. The data will be exchanged through pointers that will be either extracted from, or wrapped in a numpy object, so that the user C code will not know anything about the python objects.

### Components
- API header files
  - port functions and structures
  - run function and status structure
- Python C extension
  - Module and object definition
  - python object interface to run function
  - initializer giving access to PyObjectModel ports
  - implementation of port API functions
- Python interface
  - compile through setuptools
  - inherit or encapsulate from PyProcessModel
- Python test objects
  - minimal program compiler
  - mock port object that verifies function calls
  - post-compile topology to test connections
  - process topology and policy to test compiler

**Comment by awintel** [comment]
Looks good. One comment though:
I think you meant: "Inherit or encapsulate from CProcModel"
This is still a Python class but acting as the interface for ProcessModels implemented in C.
PyProcModels are for ProcModels implemented in Python.
