### ISSUE TITLE
Specify the minimum versions of third party dependencies

### ISSUE THREAD

**Issue by schmitts** [lava-nc/lava#132]
https://github.com/lava-nc/lava/blob/main/requirements.txt does not give the minimum versions of the dependencies.

Can you please specify them. I'll need them for #130.

**Comment by mgkwill** [comment]
@schmitts Yes. This is a good idea.

Thanks for the issue.

**Comment by mgkwill** [comment]
We've accomplished this by using poetry last release. 

See the pyproject.toml and poetry.lock file:
https://github.com/lava-nc/lava/blob/main/pyproject.toml#L45
https://github.com/lava-nc/lava/blob/main/poetry.lock

**Comment by schmitts** [comment]
Hi!

I'm in the process of putting together the Spack package (#130).

Is the list of requirements already minimal? Do we need really `nbformat`, `nbconvert` and `matplotlib` to run Lava?

Thanks,

Sebastian

**Comment by mgkwill** [comment]
Hi @schmitts, I updated our dependencies to only include:

[tool.poetry.dependencies]
python = ">=3.8, <3.11"

numpy = "^1.22.2"
scipy = "^1.8.0"
networkx = "<=2.8.7"
asteval = "^0.9.27"

`nbformat`, `nbconvert` and `matplotlib` are only used for the dev install now.
