### ISSUE TITLE
General process Var read, set and reset implementation

### ISSUE THREAD

**Issue by bamsumit** [lava-nc/lava#155]
Objective of issue: 
General process Var interaction (read, set and reset) needed for implementation of rate coded SNNs.

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request
- [ ] documentation request

**Current behavior:**

- At the moment, we need to write a separate process to do that. It would be good to have general attachable processes that can be attached to existing process and not rewrite them every time.

**Expected behavior:**

- NA

**Steps to reproduce:**

- NA

**Related code:**

```
None
```

**Other information:**

```
None
```

**Comment by PhilippPlank** [comment]
@bamsumit was this issue solved by PR #156 ?

**Comment by bamsumit** [comment]
Yes. Thanks @PhilippPlank. I will close this issue.
