### ISSUE TITLE
Ability to permute PyPort

### ISSUE THREAD

**Issue by bamsumit** [lava-nc/lava#158]
Objective of issue:
Implement Lava PyPort permute. This is typically need in CNN architectures to transition form convolution layer to dense.

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request
- [ ] documentation request

**Current behavior:**

Feature not available

**Expected behavior:**

- NA

**Steps to reproduce:**

- NA

**Related code:**

```
# expected implementation
out_port.permute([2, 1, 0]).connect(in_port)
```

**Other information:**

```
None
```

**Comment by mgkwill** [comment]
@bamsumit is this still a todo? I thought someone submitted a patch for this?

**Comment by bamsumit** [comment]
It's done.
