### ISSUE TITLE
Accessing Non-lava type process attributes in process models

### ISSUE THREAD

**Issue by ashishrao7** [lava-nc/lava#164]
Objective of issue:

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request
- [x] documentation request

**Current behavior:**

- From the documentation now, it is unclear whether a non-Lava variable defined in the process interfaces  can be  accessed in its process model (or whether this is allowable behavior). Also not very obvious is what different types of Vars can be created. For example, creating `Vars()` when the shape of the attribute is not fixed (like a user defined list) or string. A nice addition for a new developer would be a short document showing examples of initializing variables of different types and clarifying the above issue. 

**Related code:**

```
Class MyProcess(AbstractProcess):
    def __init__(self, **kwargs):
        ## Lava Var, no problems here
        self.decay_counter = Var(shape=(1, 1), init=0)

        ## are the below two commands allowed in Lava? Should they always be `Var()`? If yes, a doc defining how to do this for 
            different use-cases would be useful
        self.alpha_decay_indices = kwargs.pop("alpha_decay_schedule", [10000])    # User defined list. Can be of any size
        self.lr_decay_type =  kwargs.pop("lr_decay_type", "schedules") # a String that acts like a switch during the model execution


# pyProcess model of above Process 
@implements(proc=MyProcess, protocol=LoihiProtocol)
@requires(CPU)
class Pymyprocess(PyLoihiProcessModel):
      decay_counter: int = LavaPyType(int, np.int32)  # Lava Var
    def run_spk(self):
        if self.lr_decay_type == "schedules": # can't access lr_decay_type as of now
            pass:
```

**Comment by ashishrao7** [comment]
This PR addresses this issue https://github.com/lava-nc/lava/pull/162

**Comment by awintel** [comment]
So can this be closed?

**Comment by ashishrao7** [comment]
Not yet. The issue is about documentation. The feature has been added in a recent PR but users will largely be oblivious to these things without a document that specifies this.

**Comment by awintel** [comment]
Ok right. I just read the issue title. 
Perhaps add this as a request to the PR 162 code review in which the feature was added to make sure this gets done.
