### ISSUE TITLE
Files in compiler and runtime have BSD-3 license header

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#18]
The LICENSE files in the directory structure seem to reflect our licensing scheme but all file headers are BSD-3, including all files in `lava/magma/compiler` and `lava/magma/runtime` .

Is it meant to be that way? I was expecting all files under `compiler` and `runtime` to have LGPL-2.1 headers.

Why does the [Lava developer guide](https://lava-nc.org/developer_guide.html) state the following?
> For `lava-nc/magma/compiler` and `lava-nc/magma/runtime` use either BSD 3 or LGPL 2.1+.

If the headers are indeed incorrect, feel free to assign me.

**Comment by mgkwill** [comment]
@mathisrichter I'm checking with @awintel

**Comment by awintel** [comment]
Yes this is still a bit of a mess. The license file in the root directory should probably not make any statement about licenses in sub directories other than that all of them may get mixed licensing and the specific license will be called out in the respective files or directories.

lava/magma/{compiler/runtime} should probably also not have a general license file making general statements about all files in the directory.

We will assign licenses by file. What is currently in the repo can remain BSD. Before we introduce the Loihi compiler, we have to make some adaptations to this.
