### ISSUE TITLE
Copyright date information out of date

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#188]
Objective of issue: The copyright information in the header of all files is dated with 2021 and needs to be updated. This should be made possible globally through a script that is added to Lava.

**Lava version:**
- [x] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [ ] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request
- [ ] documentation request

**Current behavior:**

- Copyright information states 2021

**Expected behavior:**

- Copyright information states 2021-2022 (or however that must be specified in the particular licenses; could also be a list of all years in which the software was release, e.g.: 2021, 2022; check licenses)

**Steps to reproduce:**

- Open any file in Lava ;)

**Related code:**

```
# Copyright (C) 2021 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
# See: https://spdx.org/licenses/
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by mgkwill** [comment]
Yeah generally when we touch a file we should change to date range (we could do this with a script or IDE rename function): 
```
# Copyright (C) 2021-22 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
# See: https://spdx.org/licenses/
```

When we create a new file it should be for 2022:
```
# Copyright (C) 2022 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause
# See: https://spdx.org/licenses/
```

We should be enforcing both with reviews.

**Comment by mgkwill** [comment]
This is done in the latest release.
