### ISSUE TITLE
`source` command in Windows install instructions does not exist

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#19]
The install instructions for Windows in the README.md file currently include:
`source python3_venv\bin\activate.bat`

Generally, I am not sure where those commands should be executed, the Windows _cmd_ or _Powershell_? There, `source` does not exist.

I believe the correct command for _cmd_ would be
`python3_venv\Scripts\activate.bat`

I suggest to change that command in the README.md and also add a line at the beginning to explain where to execute all those commands.

**Comment by mgkwill** [comment]
This looks good to me. Trying this locally to test.

**Comment by mgkwill** [comment]
For windows cmd we should be using `python3_venv\Scripts\activate.bat` as @mathisrichter indicates.

Also we should probably say to clone with HTTPS: https://github.com/lava-nc/lava.git unless someone is contributing. Or at least point them to instructions on Github for how to setup SSH clone.

For PowerShell the commands are slightly different
```ps1
cd ~
python3 -m venv python3_venv
.\python3_venv\Scripts\Activate
pip install -U pip
# Ensure git is installed, https://git-scm.com/
git clone https://github.com/lava-nc/lava.git
cd lava
pip install ./
set PYTHONPATH=~/lava
python -m unittest discover -s tests -p "test_*.py" -vvv
```
