### ISSUE TITLE
Fix install issues in readme

### ISSUE THREAD

**Issue by mgkwill** [lava-nc/lava#203]
Objective of issue: Fix install issues in readme

**Lava version:**
- [x] **0.2.0** (current version)

**I'm submitting a ...** 
- [x] bug report
- [x] documentation request

**Current behavior:**
- Install docs are not up to date and do not support successful install.

**Expected behavior:**
- Install docs are not up to date and do not support successful install.

**Comment by SveaMeyer13** [comment]
Hi @mgkwill, 

I think the installation instruction would also need to be updated in the first tutorial.
These are the issues I encountered when trying to install on Windows:

- For windows we need to get rid of "source" in the command for activating the venv. I can activate the environment when running `python3_venv\Scripts\activate.bat `
- When running `pip install -e .`  PyBuilder fails and the first exception there is: 
``` bash 
 File "C:\Users\sveamari\PycharmProjects\lava\python3_venv\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", 
line 156, in prepare_metadata_for_build_wheel                                             
hook = backend.prepare_metadata_for_build_wheel 
AttributeError: module 'pybuilder.pep517' has no attribute 'prepare_metadata_for_build_wheel'  
```

**Comment by mgkwill** [comment]
Hi @SveaMeyer13. Thanks for letting me know. I was already working on the issue and solved it with the latest release.

Please try again with the updated install instructions: https://github.com/lava-nc/lava/blob/main/README.md#windows
