### ISSUE TITLE
Windows multiprocessing issue

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava#216]
Objective of issue:  Running multiple thread issue happened in windows while trying to run the first code example in the read.me .

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- 

**Expected behavior:**

- 

**Steps to reproduce:**

- 

**Related code:**

```
I have solved the issue (probably temporarily) by inserting the code in the if block

if __name__ == '__main__':


```

**Other information:**

```
insert the output from lava debug here

            Attempt to start a new process before the current process
            has finished its bootstrapping phase.
            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:
                if __name__ == '__main__':
                    freeze_support()
                    ...
            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.
```

**Comment by PhilippPlank** [comment]
Thank you for reporting that. Currently the workaround is to add `if __name__ == '__main__':` to your script file, but I agree it would be nicer to not have to do that.

**Comment by joyeshmishra** [comment]
Solution has been found as mentioned above. Don't think anything more needs to be done as this is not a high priority. This looks like a basic python way of implementation on windows.

Spoke to @mgkwill before closing.
