### ISSUE TITLE
New installation procedure and package appearance in python

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava#221]
Hello everyone,

I have noticed that the repo is updated so I have tried to install all of the things from scratch on my Ubuntu and Windows machines. I have faced no problems at all during the installation and the tests (Thanks for the fast reaction). But, (I am not sure why) I can not see the lava-nc repository in the pip list or pip freeze commands, however, I can only see the lava-nc by activating the virtual environment in the lava folder. In a normal way, I have tried to run the sample code in the read.me, it said there is no library called lava (as I expected) . Also, I have tried to run the second tutorial by calling the jupyter notebook in the activated environment, that did not work as well. So  I would like to know how I can make it listed amongst my python libraries.

All the best,

Ahmet

**Lava version:**
- [x] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [ ] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request
- [x] documentation request

**Comment by ahmetakman** [comment]
I have run the linting instruction and then installed it using pip with the package created in the dist folder. The problem seems solved for me.

**Comment by mgkwill** [comment]
Hi @ahmetakman. Thanks for the update.

Yes it sounds like you were installing with poetry and using the virtual env created by poetry to run the unit tests, linting etc. However you were not making this env available to your jupyter setup. 

You can install lava-nc etc. as you mentioned by just `pip install .` or `pip install -e .`, or by installing with the packages listed on the release or by installing packages created by `poetry build`. Depending on how you install it will make lava available in various environments.

It sounds like this is solved. So I will close this issue.
