### ISSUE TITLE
Replace @implements on ProcessModel with @has_models on Process

### ISSUE THREAD

**Issue by serser007** [lava-nc/lava#23]
Currently the compiler is searching for ProcessModel with 'implements' decorator in the same directory with Process.

Probably 'implements' can be changed into 'has_models' to strictly define all behaviours for Process class.
So there won't be an issue with using model from different directory and the compiler code will be simplified.

**Example:**
```
@requires(CPU)
class ProcessCPUModel(AbstractProcessModel):
    ...
@requires(GPU)
class ProcessGPUModel(AbstractProcessModel):
    ...

@has_models(ProcessCPUModel, ProcessGPUModel)
class Process(AbstractProcess):
    ...
```

**Comment by awintel** [comment]
Hi Sergey, thanks for your contribution!

It seems like you disliked the ProcessModel discovery by the compiler. Let me explain our reasoning behind that:

A Process can indeed have different ProcessModels as suggested by your decorator. However, there are issues with the @has_models decorator that we thought about before and, as a result, did not chose.

First, it creates an unnecessary dependency of the Process on the ProcessModel. The Process must know what ProcessModel it 'has' and where it is located (either in the same module or it must be imported from somewhere). With the @implements decorator, only the ProcessModel is required to specify which Process it 'implements'. The Process can be completely agnostic about that. 
Also, new ProcessModels are totally additive with an @implements approach. When someone creates a new ProcessModel variant for a Process, a developer only needs to write the code and place the file in the Process package. No other changes to existing code are necessary. With a "@has_models" decorator you always have to write a new ProcessModel (maybe in a new Python module) AND change the Process Python module as well.

Second, the requirement of the Process to 'know' about its implementing ProcessModels leads to the related problem, that not all ProcessModels will always be available to all users. Imagine a developer builds a new ProcessModel that is not going to be shared with the rest of the community. To make this ProcessModel work, requires a change in the Process that is visible to everyone. 
In particular, hardware vendors like Intel (or others possibly adopting Lava), might create certain optimized ProcessModels for their neuromorphic architectures with proprietary details that are only going to be shared with a subset of the Lava users initially as long as systems like Loihi are not available commercially.

So I hope you see that creating a two-way dependency is not favorable for several reasons.

That being said, we are aware that the current discovery process is a bit messy and needs fixing. But that is a one time effort that can be made more robust.

**Comment by awintel** [comment]
One more comment:
The messiness of the current discovery process mostly originated from the need from also wanting to discover ProcessModels in jupyter notebooks not only in *.py files. But there are better/simpler ways of doing this i.e. by using get_ipython().user_global_ns.

**Comment by mgkwill** [comment]
> Probably 'implements' can be changed into 'has_models' to strictly define all behaviours for Process class.
> So there won't be an issue with using model from different directory and the compiler code will be simplified.

Hi @serser007 thanks for the effort you put into this! We appreciate the contribution. 

As @awintel pointed out we chose to implement the compiler searching for ProcessModels intentionally. The added complexity in the compiler code was the price we thought should be paid for simplifying user additions of ProcessModels. 

Do you have any thoughts about our thinking or suggestions now that you understand the design choice?

**Comment by serser007** [comment]
Hi Andreas, thank you for your explanation!

I indeed disliked compiler's search function. Also ProcessModel with 'implements' from outside the Process directory won't be found by it (which is not obvious). But I agree that 'implements' is a better solution than 'has_models'.

**Comment by awintel** [comment]
Yes, the search is currently limited to the Process directory. This was kind of intentional to enforce that the ProcessModel is put close to the Process and overall the package containing the Process is totally self-contained. 

The package containing the Process should contain the main process.py as well as any other files required by any ProcessModel. This could also include *.c/h files for CProcessModels.

The goals it that our
/lava/proc/__init__.py
file makes importing from the process library easy like:
from lava.proc import LIF
such that users of a Process like LIF do not have to be aware of all the other stuff in that Process package; only the developer of that Process has to be.

Let us know if you have other ideas.  It's probably best to first have a discussion to clarify all questions first.
