### ISSUE TITLE
About Ubuntu 18.04 (In) Compatibility or Support 

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava#230]
Hello,
In the installation instruction there is a mark about Ubuntu 20.04 or newer version is required. Currently , I have reached a machine with Ubuntu 18.04 and seems have no chance to switch it to 20.04 because it is a fixed common machine. Since most of the dependent packages still have broad support of Ubuntu 18.04 I am curious about  what kind of incompatibility problems would I face when trying to work with Ubuntu 18.04 and lava ?

Sincerely,
Ahmet

Objective of issue:

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- 

**Expected behavior:**

- 

**Steps to reproduce:**

- 

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by ahmetakman** [comment]
I somehow managed to change it to 20.04, and there is no comment on this issue from the creators. Probably problems or compatibility issues are unknown.

**Comment by PhilippPlank** [comment]
Sorry for the late reply. We are not testing our releases of lava against Ubuntu 18.04. If the required packages work, lava might also work, but we do not test or support it.
