### ISSUE TITLE
Support Dangling Ports during Compilation and Execution

### ISSUE THREAD

**Issue by joyeshmishra** [lava-nc/lava#246]
Objective of issue: Support Dangling Ports during Compilation and Execution

**Lava version:**

- [ ] **0.4.0** (feature release)
- [ ] **0.3.1** (bug fixes)
- [x] **0.3.0** (current version)
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request
- [ ] documentation request

**Current behavior:**

- Causes compilation issue

**Expected behavior:**

- Dangling ports should be appropriately handled

**Steps to reproduce:**

- Use Tutorial 06

**Related code:**

Proposal: if you want to terminate the input end of a channel, you can use a PLUG, which won’t send anything, or a BG, which will continuously generate a constant token.  On the output end, use a GLUP which won’t sink any tokens, or BB, which sinks all tokens.

**Comment by bamsumit** [comment]
@joyeshmishra how much effort do you think it will take to 
* mark the dangling port during process graph compilation
* and not handle such ports or remove them from the graph.

That would probably be a better solution rather than using a dummy PLUG process.
