### ISSUE TITLE
Process model discovery sometimes results in repeated entries in the list

### ISSUE THREAD

**Issue by bamsumit** [lava-nc/lava#276]
Objective of issue:

**Lava version:**

- [x] **0.4.0** (current version)
- [ ] **0.3.1**
- [ ] **0.3.0**
- [ ] **0.2.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [x] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- Not always, but sometimes process model discovery results in repeated process model entries in `process_models` list.

**Expected behavior:**

- `process_models` list should have unique entries.

**Steps to reproduce:**

- 

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by mgkwill** [comment]
Was this fixed with #285 ?
