### ISSUE TITLE
Incorrect packaging

### ISSUE THREAD

**Issue by nurmukhametov** [lava-nc/lava#28]
It looks like build scripts pack lava incorrectly.
For example:
```bash
> wget https://github.com/lava-nc/lava/releases/download/v0.1.0/lava-nc-0.1.0.tar.gz
> pip install lava-nc-0.1.0.tar.gz
> python -c "import lava"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lava'
```

`/usr/lib/python3.9/site-packages/` contains
```
lava_nc.egg-info/
magma/
proc/
tutorials/
utils/
```
but no `lava` directory exists.

Moreover, uninstalling attempts to delete everything in `/usr/lib/python3.9/site-packegs/`
```bash
> sudo pip uninstall lava-nc
Found existing installation: lava-nc 0.1.0
Uninstalling lava-nc-0.1.0:
  Would remove:
    /usr/lib/python3.9/site-packages/*
  Would not remove (might be manually added):
...
```

**Comment by mgkwill** [comment]
Hi @nurmukhametov. Thanks for filing this issue! I'm taking a look now.

**Comment by mgkwill** [comment]
It appears that [pybuilder](https://pybuilder.io/documentation/plugins#python-deployment) needs a top level src dir before python modules.

Pointing pybuilder to 'lava' as the source directory, it assumes this directory is not part of the src and only processes the directories below this ignoring the __init__.py etc.

The solution for now seems to be to add an empty src directory above lava and specify 'src' as the build path. Opening a pull request with this change.

**Comment by mgkwill** [comment]
I've updated the release binary. It should have the directory structure:

lava-nc-0.1.0/
├── lava
│   ├── __init__.py
│   ├── magma
│   ├── proc
│   ├── tutorials
│   └── utils
├── lava_nc.egg-info
│   ├── dependency_links.txt
│   ├── namespace_packages.txt
│   ├── PKG-INFO
│   ├── requires.txt
│   ├── SOURCES.txt
│   ├── top_level.txt
│   └── zip-safe
├── PKG-INFO
├── setup.cfg
└── setup.py

I'm tested and can install with `pip install lava-nc-0.1.0.tar.gz`

Also I can import lava, import lava.magma using the above install into a venv.
