### ISSUE TITLE
Refractory period for LIF Process

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#282]
### User story

As a user, I want the LIF Process to support a refractory period after spiking.

Note: A side effect of this missing feature is that the current Python implementation resets the voltage to 0 after a spike, whereas on the hardware it is reset to 128 (which implements the refractory period). The original story was a bug around that.

### Conditions of satisfaction
- to be determined

### Acceptance tests
- to be determined

**Comment by GitUser369** [comment]
I believe that this is just a reporting difference. The internal (hidden) states should be the same. You can confirm this by looking at when subsequent spikes occur.

**Comment by mathisrichter** [comment]
The state of the voltage on Loihi is in fact 128 after a spike. As you are correctly pointing out, that initial voltage does not have an impact on its later evolution.

I think this behavior should still be reflected in the Python ProcessModel to enable easy comparison between results from hardware and simulation.

**Comment by mathisrichter** [comment]
This story is really about adding support for a refractory period in the LIF neuron. The different behavior in the bit-accurate Python ProcessModel is just an artifact of that missing feature. I have changed the story to reflect this.

**Comment by tim-shea** [comment]
#655 was solved with a merged refractory process.
