### ISSUE TITLE
Tutorial on E/I network

### ISSUE THREAD

**Issue by ackurth-nc** [lava-nc/lava#308]
As part of the tutorials, it would be good to have a tutorial on a standard network of recurrently connected excitatory and inhibitory neurons. 

**I'm submitting a ...** 
- [ ] bug report
- [ ] feature request
- [x] documentation request

**Comment by awintel** [comment]
@ackurth-nc  Can this be closed?

**Comment by ackurth-nc** [comment]
Yes.
