### ISSUE TITLE
MNIST Tutorial errors out when creating object of class PyImageClassifierModel()

### ISSUE THREAD

**Issue by GitUser369** [lava-nc/lava#312]
Objective of issue: Repair lava/tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb so that it runs without issues

**Lava version:**

- [x] **0.4.0** (current version)

**I'm submitting a ...** 

- [x] bug report

**Current behavior:**

- Errors our during run time

In the 9th cell , during execution of:

    mnist_clf.run(
        condition=RunSteps(num_steps=num_steps_per_image),
        run_cfg=Loihi1SimCfg(select_sub_proc_model=True,
                             select_tag='fixed_pt'))

We get the following error

![image](https://user-images.githubusercontent.com/78598691/185630464-d1f402c8-b43b-4882-b065-eeecbdc88b41.png)

**Expected behavior:**

**Steps to reproduce:**

- Run the tutorial lava/tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb

**Related code:**
lava/tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb

Problem can be fixed by defining the shape of the Dense() layer as follows

```
class PyImageClassifierModel(AbstractSubProcessModel):
    def __init__(self, proc):
        self.dense0 = Dense(weights=proc.w_dense0.init, shape=proc.w_dense0.init.shape)
        self.lif1 = LIF(shape=(64,), bias_mant=proc.b_lif1.init, vth=400,
                        dv=0, du=4095)
        self.dense1 = Dense(weights=proc.w_dense1.init, shape=proc.w_dense1.init.shape)
        self.lif2 = LIF(shape=(64,), bias_mant=proc.b_lif2.init, vth=350,
                        dv=0, du=4095)
        self.dense2 = Dense(weights=proc.w_dense2.init, shape=proc.w_dense2.init.shape)
        self.output_lif = LIF(shape=(10,), bias_mant=proc.b_output_lif.init,
                              vth=1, dv=0, du=4095)
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by GitUser369** [comment]
This was a local pyenv problem. Somehow two different versions of lava were installed locally. When version 0.4.0 is properly installed and used, this problem no longer exists.

**Comment by drader** [comment]
I am getting the same problem;

the system is;
macOS
lava-nc v0.9.0
python 3.9.18

I've reinstalled and made pytest for lava. However, they still couldn't solve the problem. Would you happen to have any idea or solution for this issue? @JuliaA369
