### ISSUE TITLE
Monitor() doesn't work when using 'bit_accurate_loihi' tag during run time

### ISSUE THREAD

**Issue by JuliaA369** [lava-nc/lava#319]
Objective of issue: Allow Monitor() class to work when using 'bit_accurate_loihi' tag for Loihi1SimCfg when running a Process. 

**Lava version:**

- [x] **0.4.0** (current version)

**I'm submitting a ...** 

- [x ] feature request

**Current behavior:**

-  Run time error when using Monitor() and `run_cfg = Loihi1SimCfg(select_tag='bit_accurate_loihi')`

**Expected behavior:**

- Should successfully create a Monitor object so that we can probe voltages, currents, etc

**Steps to reproduce:**

- create a Monitor() object
- probe() the monitor
- run a process with `run_cfg = Loihi1SimCfg(select_tag='bit_accurate_loihi')`

**Related code:**

Just run through the following tutorial:
https://github.com/lava-nc/lava/blob/main/tutorials/end_to_end/tutorial00_tour_through_lava.ipynb

But change `run_cfg = Loihi1SimCfg()` to `run_cfg = Loihi1SimCfg(select_tag='bit_accurate_loihi')`

**Other information:**

Currently getting the following error
```
AssertionError: [Loihi1SimCfg]: No ProcessModels found with tag 'bit_accurate_loihi' for Process Process_22::Monitor.
```

**Comment by weidel-p** [comment]
Thanks for this bug report. I was able to reproduce the faulty behavior in the current version 0.4 but the problem seems already to be resolved in the current main branch. Hence, next release will also cover this fix.

**Comment by PhilippPlank** [comment]
This issue is solved with the newer lava releases, hence I will close it.
