### ISSUE TITLE
Error in Loihi1HwCfg and Loihi2HwCfg does not allow the use of tags with CLoihiProcesModel

### ISSUE THREAD

**Issue by waltergallegog** [lava-nc/lava#325]
Objective of issue: Report probable issue in function `_order_according_to_resources` of classes `Loihi1HwCfg` and `Loihi2HwCfg` that does not allow the use of tags for `CLoihiProcesModel`.

**Lava version:**

- [x] **0.4.0** (current version)

**I'm submitting a ...** 

- [x] bug report

**Current behavior:**

When using `tags` and `CLoihiProcessModel`, the following error is thrown:
```
  File ".../lava/magma/core/run_configs.py", line 314, in <listcomp>
    if self.select_tag in proc_models[idx].tags]
TypeError: list indices must be integers or slices, not ABCMeta
```

**Expected behavior:**

No error thrown.

**Steps to reproduce:**

 - Define a `CLoihiProcessModel` with tag(s)
 - Try to run by using a Hw configuration, like `Loihi1HwCfg` and a tag

**Other information:**

I believe the issue is on lines:
https://github.com/lava-nc/lava/blob/3698a0b1b95ded1a568c96e44f8db18c577ab989/src/lava/magma/core/run_configs.py#L396
https://github.com/lava-nc/lava/blob/3698a0b1b95ded1a568c96e44f8db18c577ab989/src/lava/magma/core/run_configs.py#L454

The var `proc_models_c` should be a list of indices, not a list of models.

`proc_models_py` and `proc_models_nc` do not have this issue:
https://github.com/lava-nc/lava/blob/3698a0b1b95ded1a568c96e44f8db18c577ab989/src/lava/magma/core/run_configs.py#L391

**Comment by joyeshmishra** [comment]
We are picking this up now. Will try to make it for next release.

**Comment by ysingh7** [comment]
This issue has been fixed and will be released in next release.
