### ISSUE TITLE
Dense Process Documentation missing

### ISSUE THREAD

**Issue by ashishrao7** [lava-nc/lava#331]
https://github.com/lava-nc/lava/blob/780ee5a0ffece86a1980287618ca730fde90820d/src/lava/proc/dense/process.py#L58
This parameter seems to be deprecated instead being replaced by `num_message_bits` which doesn't seem to be documented

**Comment by awintel** [comment]
Did this get fixed for v0.5.0?

**Comment by weidel-p** [comment]
Yes, that got fixed. I close the issue.
