### ISSUE TITLE
Terminate gracefully if Runtime.stop() is called during execution

### ISSUE THREAD

**Issue by awintel** [lava-nc/lava#35]
We are currently in a transitory state where Runtime.wait() and Runtime.pause() is not fully implemented so running in non-blocking mode does actually not make any sense. So perhaps we should just not allow blocking=False right now and throw an error as long as this is not implemented. 

But regardless of that, when someone runs with blocking=False, then there is the potential that users call stop() while the underlying processes are still not done running.
This does currently end in not very meaningful error messages saying that some processes did not TERMINATE but are only DONE. Obviously this should be fixed.

The expected behavior would be:
If the Runtime gets stopped while still running, the TERMINATE token gets distributed to all processes. All processes stop at the next possible iteration and then they should acknowledge with the TERMINATED token. If not, the error message should specify why that's not possible.

**Comment by PhilippPlank** [comment]
Pull Request #67 disables the usage of blocking=False for now (error + message) until this issue is resolved.
