### ISSUE TITLE
Something is embarrassingly slow (with current message passing backend?)

### ISSUE THREAD

**Issue by awintel** [lava-nc/lava#36]
@ashishrao7's quadratic programming process in lava-optim seems to be super slow compared to a pure numpy implementation. Since the only main difference between the two implementation seems to be the event-based message passing in between, we need to figure out why that is the case.

**Comment by ashishrao7** [comment]
To provide more context the process model for the solver is shown below:
![image](https://user-images.githubusercontent.com/12975862/140792985-a262e211-3d2e-4a2d-9a5a-1ddeb4fdbe95.png)
The update equations (top right) running in numpy take ~20ms for 1000 iterations.  The process models implementing the same update equations in LAVA when run on the same machine take about 100 seconds for 1000 iterations.

**Comment by awintel** [comment]
Please also check what is setup time and what is actual execution time.

**Comment by ashishrao7** [comment]
Adding the profiling results on an on some small QPs. Most of the time seems to be spend on some acquire method of a thread.lock object
Added scripts for problems of size 
3x3 with 2 constraints =>  ports of size (3,1) and (2,1),
[3x3QPprofiling.txt](https://github.com/lava-nc/lava/files/7528940/3x3QPprofiling.txt)

4x4 with 3 constraints =>  ports of size (4,1) and (3,1)
[4x4QPprofiling.txt](https://github.com/lava-nc/lava/files/7528941/4x4QPprofiling.txt)

5x5 with 3 constraints =>  ports of size (5,1) and (3,1)
[5x5QPprofiling.txt](https://github.com/lava-nc/lava/files/7528943/5x5QPprofiling.txt)
