### ISSUE TITLE
Arbitrary Process-network topologies

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#396]
### User story
As a user, I want to connect Lava Processes with each other to form arbitrarily complex Process-network topologies. This enables me to develop any neuromorphic architecture I could dream up.

### Conditions of satisfaction
- We have established a systematic overview of all qualitatively different types/combinations of topologies.
- We have unit/integration tests for all those types above.
- If a topology is supported
  - it is demonstrated by a unit test.
- If a topology is not supported
  - a unit test ensures that an error message is thrown that is meaningful to users.
  - a feature request is filed to support that topology.

### Acceptance tests
- Systematically test the following types of network topologies and **combinations thereof**.
- Test recurrent topologies.
- Test nested recurrent topologies.
- Test with different types of ProcModels.
- Test with multiple inputs from Py/C.
- Test with multiple outputs from Py/C.
- Test recurrent loops through Py/C back into Nc (and vice versa).
- Test joining topologies
  - that are supported (e.g., two Dense to one LIF).
  - that are not supported (e.g., two LIF to one Dense).
- Test forking topologies
  - that are supported (e.g., one LIF to two Dense).
  - that are not supported (e.g., one Dense to two LIF).
- Test with hierarchical Processes. 
- Test with many Processes.
- (to be continued)

**Comment by tim-shea** [comment]
@mathisrichter I think this has been mostly addressed for some time now, though the level of comprehensive testing you described is not in place. Please reopen if you think otherwise.
