### ISSUE TITLE
Unable to load pretrained weights in MNIST classification tutorial

### ISSUE THREAD

**Issue by AlessandroPierro** [lava-nc/lava#434]
Objective of issue: Report possible bug in [MNIST classification tutorial](https://github.com/lava-nc/lava/blob/main/tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb).

**Lava version:**

- [x] **0.5.0** (current version)

**I'm submitting a ...** 
- [x] bug report

**Current behavior:**

- The code fails to load the pretrained weights [mnist_pretrained.npy](https://github.com/lava-nc/lava/blob/main/tutorials/end_to_end/mnist_pretrained.npy).

**Expected behavior:**

- Correctly load the pretrained weights

**Steps to reproduce:**

- Follow the installation instructions and run the tutorial.

**Related code:**

The error can be also reproduced by simply loading the serialized weights using numpy.
```python
IPython 8.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np

In [3]: np.load("/home/apierro/temp/lava/tutorials/end_to_end/mnist_pretrained.npy", allow_pickle=True)
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
File ~/temp/lava/.venv/lib/python3.8/site-packages/numpy/lib/npyio.py:421, in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    420 try:
--> 421     return pickle.load(fid, **pickle_kwargs)
    422 except Exception as e:

UnpicklingError: invalid load key, 'v'.

The above exception was the direct cause of the following exception:

UnpicklingError                           Traceback (most recent call last)
Cell In [3], line 1
----> 1 np.load("/home/apierro/temp/lava/tutorials/end_to_end/mnist_pretrained.npy", allow_pickle=True)

File ~/temp/lava/.venv/lib/python3.8/site-packages/numpy/lib/npyio.py:423, in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    421     return pickle.load(fid, **pickle_kwargs)
    422 except Exception as e:
--> 423     raise pickle.UnpicklingError(
    424         f"Failed to interpret file {file!r} as a pickle") from e

UnpicklingError: Failed to interpret file '/home/apierro/temp/lava/tutorials/end_to_end/mnist_pretrained.npy' as a pickle
```

**Other information:**

The tests have been executed on WSL2.

**Comment by jorchard** [comment]
I get the same error on Mac OS using a Debian-based Docker container. I also can't read it using my base system:
```
> import pickle
> f = open('mnist_pretrained.npy', 'rb')
> foo = pickle.load(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by mgkwill** [comment]
Hi All.

I have a sneaking suspicion this is an issue with running with the placeholder git lfs file and not the actual file.

Can you try `git lfs fetch` and `git lfs pull` and try again?

Git LFS stores binary or large files by putting a placeholder file that describes the location of the actual file, but to get the file one needs to pull it using git lfs as above.

Thanks,
Marcus

**Comment by AlessandroPierro** [comment]
Hi @mgkwill, thanks for the reply.

This solves the issue for me. 👍
