### ISSUE TITLE
Improve LoihiProtocol to allow requesting MANAGEMENT instead of always unconditionally executing MANAGEMENT

### ISSUE THREAD

**Issue by awintel** [lava-nc/lava#49]
Right now we have two issues in the RuntimeService:
1. The Loihi Protocol is hard-coded. This needs to be factored out but can be done in a bit.
2. The current implementation of the LoihiProtocol always executes MANAMEMENT and LEARNING phases unconditionally which is unnecessarily wasteful and anyways not how Loihi actually work. In Loihi processes can request PRE_MGMT, LRN or POST_MGMT in the preceding phase which is way more efficient. We need to to support this as well in simulation.

**Comment by ysingh7** [comment]
Has been Fixed
