### ISSUE TITLE
Simplify lava-nc/lava and lava-nc.org landing pages and reduce content duplication

### ISSUE THREAD

**Issue by awintel** [lava-nc/lava#50]
Right now there is a lot of content duplication in the lava readme and the lava-nc.org landing page.

Now that the project has been launched and we have more and more actual code-content, we should revisit both pages and simplify them and avoid that we have to manage the same content in different places. 

The lava readme should be come shorter and simpler and only reference key information in other places. 
The content on the lava-nc.org page could be broken up and put on different sub pages as well.

In addition, we should think about search engine optimization for lava-nc.org so that the page structure gets displayed better by google.

**Comment by mgkwill** [comment]
This is done in the latest release.
