### ISSUE TITLE
Initialization of Dense with all-zero weights

### ISSUE THREAD

**Issue by PhilippPlank** [lava-nc/lava#501]
**Describe the bug**

The automatic determination of the weight exponent given the weights does fail, if all weights are 0. As this is used in the general Dense process for Loihi2HwCfg (running on Loihi 2), initializing weights with just 0 is currently not possible.

**To reproduce current behavior**
- Configure as LIF->Dense network with the Dense process from the process library and set the initial weights to 0. Run the network with Loihi2HwCfg (running on Loihi 2).
```python
weights = np.zeros((3,4))

inport_plug = LIF(shape=(4,), vth=10, du=0, dv=0, bias_mant=80)

dense_weights = Dense(weights=weights, 
                      use_graded_spike=False)

lif_layer = LIF(shape=(3,), vth=10, du=4095, dv=0, bias_mant=0)
inport_plug.s_out.connect(dense_weights.s_in)
dense_weights.a_out.connect(lif_layer.a_in)

lif_layer.run(condition=RunSteps(num_steps=run_steps), 
                 run_cfg=Loihi2HwCfg())

v_final = lif_layer.v.get()
lif_layer.stop()
```
2. I get this error ...
```
File ~/frameworks.ai.lava.lava-loihi/.venv/lib/python3.8/site-packages/lava/utils/weightutils.py:75, in optimize_weight_bits(weights, sign_mode, loihi2)
     56 """Optimizes the weight matrix to best fit in Loihi's synapse.
     57 
     58 Parameters
   (...)
     71     An object that wraps the optimized weight matrix and weight parameters.
     72 """
     73 _validate_weights(weights, sign_mode)
---> 75 weight_exp = _determine_weight_exp(weights, sign_mode)
     76 num_weight_bits = _determine_num_weight_bits(weights, weight_exp, sign_mode)
     78 weights = np.left_shift(weights.astype(np.int32), int(-weight_exp))

File ~/frameworks.ai.lava.lava-loihi/.venv/lib/python3.8/site-packages/lava/utils/weightutils.py:148, in _determine_weight_exp(weights, sign_mode)
    145 elif sign_mode == SignMode.EXCITATORY:
    146     scale = 255 / max_weight
--> 148 scale_bits = int(np.floor(np.log2(scale)))
    149 if sign_mode == SignMode.MIXED:
    150     scale_bits += 1

OverflowError: cannot convert float infinity to integer
```

**Expected behavior**
As a user, I want the automatic determination of weight exponent and sign in `Dense` to work also when all weights are zero.

**Environment (please complete the following information):**
 - Device: Intel cloud
 - OS: Linux
 - Lava 0.5.1

### Tasks

- [x] Implement the conversion which accepts all-zero weight matrices without throwing an error for Loihi 2 and CPU backend + writing unit tests (1/2 day)
- [ ] Review the change and merge it (1/2 day)

**Comment by mathisrichter** [comment]
@PhilippPlank Is this the same problem as reported in [#59](https://github.com/intel-collab/frameworks.ai.lava.lava-loihi/issues/59)?

**Comment by PhilippPlank** [comment]
Yes. I guess we can close this then. Sorry for overlooking the issue.

**Comment by mathisrichter** [comment]
Reopening the issue here as the original issue was incorrectly filed internally.
