### ISSUE TITLE
Add ability to change Loihi Learning Rule during runtime

### ISSUE THREAD

**Issue by JuliaA369** [lava-nc/lava#542]
Objective of issue: It would be greatly desirable if we could change parameters of a Loihi2FLearningRule during runtime, particularly for the CPU and/or GPU implimenations.

**Lava version:**

- [ ] **0.6.0** (feature release)
- [ ] **0.5.1** (bug fixes)
- [x] **0.5.0** (current version)
- [ ] **0.4.1**
- [ ] **0.4.0**
- [ ] **0.3.0**
- [ ] **0.1.2**

**I'm submitting a ...** 

- [ ] bug report
- [x] feature request
- [ ] documentation request

**Current behavior:**

- The ability to change a learning rule during runtime is needed in order to do research into optimizing learning rules (meta-learning). One option would be to recreate the learning synapse over and over again. Besides being slower, this option is not a possibility because of issue 336 (https://github.com/lava-nc/lava/issues/336). 

**Expected behavior:**

It would be amazing if there was something like there is for Dense synapse where you can do something like:

`dense.weights.set()`

Except in this case it would be providing something like:
`lr.dw.set()`
`lr.dt.set()`
`lr.x1_impulse.set()`
`lr.x1_tau.set()`
`lr.y1_impulse.set()`
`lr.y1_tau.set()`
`lr.t_epoch.set()`

This would allow us to perform offline trainings that we could then deploy to hardware. 

**Steps to reproduce:**

- 

**Related code:**

```
num_steps = 5000
du = 10
dv = 100
vth = 4900
if __name__ == "__main__":
    # Create processes
    lif1 = LIF(shape=(3, ),                         
            vth=vth,                             
            dv=dv,                              
            du=du,                              
            bias_mant=(1, 3, 2),           
            name="lif1")

    lr= Loihi2FLearningRule(dw=dw,
                               x1_impulse=x1_impulse,
                               x1_tau=x1_tau,
                               y1_impulse=y1_impulse,
                               y1_tau=y1_tau,
                               t_epoch=t_epoch)

    plast_conn = LearningDense(weights=wgt_plast_conn,
                               learning_rule=stdp,
                               name='plastic_dense')

    lif1.s_out.connect(plast_conn .s_in)
    dense.a_out.connect(lif2.a_in)

    for k in range(num_steps):

        if k > 0:
            lr.dw.set(dw_new)
            lr.x1_impulse.set(x1_impulse_new)
            lr.x1_tau.set(x1_tau_new)
            lr.y1_impulse.set(y1_impulse_new)
            lr.y1_tau.set(y1_tau_new)
            lr.t_epoch.set(t_epoch_new)
        
        lif2.run(condition=RunSteps(num_steps=10),
            run_cfg=Loihi1SimCfg(select_tag="fixed_pt"))

    lif2.stop()


```

**Other information:**

```
insert the output from lava debug here
```

**Comment by weidel-p** [comment]
Thanks for this suggestion, that would be a great feature to support. It should be straight forward to implement that for the CPU/Python version but might need some work on hardware. @mz-ncl could you comment if this is possible at all?

**Comment by JuliaA369** [comment]
Thanks @weidel-p. I've edited the issue to clarify that we are requesting this for CPU (and potentially future GPU) implementations, and not for hardware.

**Comment by weidel-p** [comment]
Hi @JuliaA369, thanks for your patience. We added this feature now in #622 which is now merged to the main branch. Please take a look.

**Comment by JuliaA369** [comment]
Thanks! This is exciting! Looking forward to trying this out soon.

**Comment by tim-shea** [comment]
@weidel-p it looks like this was fixed already. Please reopen and clarify what else needs to be done if that's not correct.
