### ISSUE TITLE
Problem with tutorialx04_stdp_on_chip

### ISSUE THREAD

**Issue by gjkunde** [lava-nc/lava#543]
Running the first cell I get:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 6
      3 import matplotlib.pyplot as plt
      5 from lava.proc.learning_rules.stdp_learning_rule import STDPLoihi
----> 6 from lava.proc.lif.process import LIF, LearningLIF
      7 from lava.proc.io.source import RingBuffer as SpikeIn
      8 from lava.proc.dense.process import LearningDense, Dense

File ~/lava/lava_nx_env/lib/python3.8/site-packages/lava/proc/lif/process.py:12
      6 import typing as ty
      8 from lava.magma.core.learning.learning_rule import (
      9     LoihiLearningRule,
     10     Loihi2FLearningRule,
     11 )
---> 12 from lava.magma.core.process.process import LogConfig, AbstractProcess
     13 from lava.magma.core.process.variable import Var
     14 from lava.magma.core.process.ports.ports import InPort, OutPort

File ~/lava/lava_nx_env/lib/python3.8/site-packages/lava/magma/core/process/process.py:19
     17 from lava.magma.core.process.variable import Var
     18 from lava.magma.core.run_conditions import AbstractRunCondition
---> 19 from lava.magma.core.run_configs import RunConfig
     20 from lava.magma.runtime.runtime import Runtime
     21 from lava.magma.runtime.runtime_services.enums import LoihiVersion

File ~/lava/lava_nx_env/lib/python3.8/site-packages/lava/magma/core/run_configs.py:16
     14 try:
     15     from lava.magma.core.model.c.model import CLoihiProcessModel
---> 16     from lava.magma.core.model.nc.model import AbstractNcProcessModel
     17 except ImportError:
     18     class AbstractCProcessModel:

File ~/lava/lava_nx_env/lib/python3.8/site-packages/lava/magma/core/model/nc/model.py:22
     19 import typing as ty
     21 from lava.magma.core.model.model import AbstractProcessModel
---> 22 from lava.magma.core.model.nc.table_container import TableContainer
     25 class AbstractNcProcessModel(AbstractProcessModel, ABC):
     26     """Abstract interface for NeuroCore ProcessModels
     27 
     28     Example for how variables might be initialized:
   (...)
     32         du: int =          LavaNcType(int,        np.uint16, precision=12)
     33     """

File ~/lava/lava_nx_env/lib/python3.8/site-packages/lava/magma/core/model/nc/table_container.py:23
     20 import numpy as np
     21 import numpy.typing as npty
---> 23 from lava.magma.core.model.nc.var import NcVar
     24 from lava.magma.core.process.ports.ports import AbstractPort
     25 from lava.magma.core.process.variable import Var

File ~/lava/lava_nx_env/lib/python3.8/site-packages/lava/magma/core/model/nc/var.py:27
     21 from numpy import typing as npty
     23 from lava.magma.core.process.variable import Var
     26 @dataclass
---> 27 class NcVar:
     28     """Class for the value of the dict TableContainer.var_map"""
     29     def __init__(self, d_type: type, precision: int):

File ~/lava/lava_nx_env/lib/python3.8/site-packages/lava/magma/core/model/nc/var.py:41, in NcVar()
     37     self.forward_map_fxn: types.FunctionType = None
     38     self.backward_map_fxn: types.FunctionType = None
     40 def fill_var_dict(self, var: Var, htr_tbl: 'HeteroTable', tbl_idx: int,
---> 41                   row_idx: npty.NDArray[np.int], col_idx: int):
     42     num_rows = np.prod(var.shape) if len(var.shape) > 1 else var.shape[0]
     43     if len(row_idx) != num_rows:

File ~/lava/lava_nx_env/lib/python3.8/site-packages/numpy/__init__.py:284, in __getattr__(attr)
    281     from .testing import Tester
    282     return Tester
--> 284 raise AttributeError("module {!r} has no attribute "
    285                      "{!r}".format(__name__, attr))

AttributeError: module 'numpy' has no attribute 'int'

**Comment by gjkunde** [comment]
It turns out the error only occurs with a fresh installation on the inrc node following the tutorial which uses Numpy 1.24.0,
when dialed back to Numpy 1.23.5 the error does not show. While it needs fixing 1.23.5 is a temporary solution.

**Comment by PhilippPlank** [comment]
Thanks for reporting this, I have also stumbled across this issue. The new numpy release 2 days ago did not work well with our own release last week. Working on a fix.

**Comment by weidel-p** [comment]
I'm closing this issue as this should be fixed already.
