### ISSUE TITLE
dataloader.s_out is (1,1). And net.inp shape is (1,) . Getting "Shapes are incompatible" error. I have only 1 neuron at the input layer. And 1D time series data of dim (1x187)

### ISSUE THREAD

**Issue by Ajay-B-S** [lava-nc/lava#544]
from lava.proc import io

##Instantiate the processes
dataloader = io.dataloader.SpikeDataloader(dataset=testing_set)
output_logger = io.sink.RingBuffer(shape=net.out_layer.shape, buffer=num_steps)
gt_logger = io.sink.RingBuffer(shape=(1,), buffer=num_steps)

##Connect the input to the network:
dataloader.ground_truth.connect(gt_logger.a_in)
print(dataloader.ground_truth.shape)
print(gt_logger.a_in.shape)
print(dataloader.s_out.shape)
print(net.inp.shape)

dataloader.s_out.connect(net.inp)

##Connect network-output to the output process
net.out_layer.out.connect(output_logger.a_in)

=====================================================================
Output:

torch.Size([1])
(1,)
(1, 1)
(1,)
AssertionError Traceback (most recent call last)
Input In [26], in <cell line: 16>()
12 print(dataloader.s_out.shape)
13 print(net.inp.shape)
---> 16 dataloader.s_out.connect(net.inp)
18 # Connect network-output to the output process
19 net.out_layer.out.connect(output_logger.a_in)

File ~/ajay_venv/src/lava-nc/src/lava/magma/core/process/ports/ports.py:439, in OutPort.connect(self, ports)
428 def connect(
429 self, ports: ty.Union["AbstractIOPort", ty.List["AbstractIOPort"]]
430 ):
431 """Connects this OutPort to other InPort(s) of another process
432 or to OutPort(s) of its parent process.
433
(...)
437 The AbstractIOPort(s) to connect to.
438 """
--> 439 self._connect_forward(to_list(ports), AbstractIOPort)

File ~/ajay_venv/src/lava-nc/src/lava/magma/core/process/ports/ports.py:128, in AbstractPort._connect_forward(self, ports, port_type, assert_same_shape, assert_same_type)
117 def _connect_forward(
118 self,
119 ports: ty.List["AbstractPort"],
(...)
122 assert_same_type: bool = True,
123 ):
124 """Creates a forward connection from this AbstractPort to other
125 ports by adding other ports to this AbstractPort's out_connection and
126 by adding this AbstractIOPort to other port's in_connections."""
--> 128 self._validate_ports(
129 ports, port_type, assert_same_shape, assert_same_type
130 )
131 # Add other ports to this port's output connections
132 self._add_outputs(ports)

File ~/ajay_venv/src/lava-nc/src/lava/magma/core/process/ports/ports.py:99, in AbstractPort._validate_ports(self, ports, port_type, assert_same_shape, assert_same_type)
97 if assert_same_shape:
98 if self.shape != p.shape:
---> 99 raise AssertionError("Shapes {} and {} "
100 "are incompatible."
101 .format(self.shape, p.shape))

AssertionError: Shapes (1, 1) and (1,) are incompatible.

**Comment by mathisrichter** [comment]
The problem was in the way the `testing_set` was generated.
