### ISSUE TITLE
Error from channel_map.py: "KeyError: <lava.magma.core.process.ports.ports.ReshapePort object at 0x7f22a7f1a940>" for the ports

### ISSUE THREAD

**Issue by Ajay-B-S** [lava-nc/lava#546]
**Error**:
File ~/ajay_venv/src/lava-nc/src/lava/magma/compiler/channel_map.py:123, in␣ChannelMap.get_port_initializer(self, port)
122 def get_port_initializer(self, port):
**--> 124 return self._initializers_lookup[port]**
**KeyError: <lava.magma.core.process.ports.ports.ReshapePort object at 0x7f22a7f1a940>**

===================================================================================
Input is ECG with size 1x187 and input spikes are with payload and number of input neurons are 1. And 5 classes at output.

**Code**: Output logger is not connected to any other unit as of now. 

```python
from lava.proc import io
dataloader = io.dataloader.SpikeDataloader(dataset=testing_set)
output_logger = io.sink.RingBuffer(shape=net.out_layer.shape, buffer=num_steps)
gt_logger = io.sink.RingBuffer(shape=(5,1,1), buffer=num_steps)

dataloader.ground_truth.connect(gt_logger.a_in)
dataloader.s_out = dataloader.s_out.flatten()
print(dataloader.ground_truth.shape)
print(gt_logger.a_in.shape)
print(dataloader.s_out.flatten().shape)
print(net.inp.shape)
print(output_logger.a_in.shape)
print(net.out_layer.out.shape)
dataloader.s_out.flatten().connect(net.inp)

net.out_layer.out.connect(output_logger.a_in)
```

prints from above cell:

```
torch.Size([5, 1, 1])
(5, 1, 1)
(1,)
(1,)
(5,)
(5,)
```
**Next cell:**

```python
from lava.magma.core.run_configs import Loihi2SimCfg, Loihi2HwCfg
from lava.magma.core.run_conditions import RunSteps
from lava.proc import io
from lava.magma.core.process.variable import Var
from lava.magma.core.process.ports.ports import RefPort
from lava.magma.core import run_configs as rcfg

net.run(condition=RunSteps(num_steps=num_steps), run_cfg=rcfg.Loihi1SimCfg())
output = output_logger.data.get().flatten()
gts = gt_logger.data.get().flatten()[::steps_per_sample]
net.stop()
result = output[readout_offset::steps_per_sample]
```

=============================================================================
Debug prints:

 proc is 
| Type   | W | H | C | ker | str | pad | dil | grp |delay|
|Dense | 1| 1| 16| | | | | |False|
|Dense | 1| 1| 64| | | | | |False|
|Dense | 1| 1| 32| | | | | |False|
|Dense | 1| 1| 5| | | | | |False|

Debug prints in channel_map.py 123:
def ChannelMap.get_port_initializer(self, port)
122 def get_port_initializer(self, port):
--> 123 print(f'port is {port} and initializers_lookup is {self._initializers_lookup[port]}')
124 return self._initializers_lookup[port]

port is <lava.magma.core.process.ports.ports.OutPort object at 0x7f21ec499b50>
and initializers_lookup is PortInitializer(name='s_out', shape=(16,),
d_type=<class 'float'>, port_type='OutPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.InPort object at 0x7f21ec4a83a0>
and initializers_lookup is PortInitializer(name='s_in', shape=(16,),
d_type=<class 'bool'>, port_type='InPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.OutPort object at 0x7f21ec4ac640>
and initializers_lookup is PortInitializer(name='s_out', shape=(32,),
d_type=<class 'float'>, port_type='OutPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.InPort object at 0x7f21ec4acee0>
and initializers_lookup is PortInitializer(name='s_in', shape=(32,),
d_type=<class 'bool'>, port_type='InPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.OutPort object at 0x7f21ec4996d0>
and initializers_lookup is PortInitializer(name='a_out', shape=(16,),
d_type=<class 'float'>, port_type='OutPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.InPort object at 0x7f21ec499b20>
and initializers_lookup is PortInitializer(name='a_in', shape=(16,),
d_type=<class 'float'>, port_type='InPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.OutPort object at 0x7f21ec4a83d0>
and initializers_lookup is PortInitializer(name='a_out', shape=(64,),
d_type=<class 'float'>, port_type='OutPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.InPort object at 0x7f21ec4a8850>
and initializers_lookup is PortInitializer(name='a_in', shape=(64,),
d_type=<class 'float'>, port_type='InPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.OutPort object at 0x7f21ec4a8880>
and initializers_lookup is PortInitializer(name='s_out', shape=(64,),
d_type=<class 'float'>, port_type='OutPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.InPort object at 0x7f21ec4ac160>
and initializers_lookup is PortInitializer(name='s_in', shape=(64,),
d_type=<class 'bool'>, port_type='InPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.OutPort object at 0x7f22a7f1a3d0>
and initializers_lookup is PortInitializer(name='ground_truth',
shape=torch.Size([5, 1, 1]), d_type=<class 'float'>, port_type='OutPort',
size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.InPort object at 0x7f22a7f1a970>
and initializers_lookup is PortInitializer(name='a_in', shape=(5, 1, 1),
d_type=<class 'float'>, port_type='InPort', size=64, transform_funcs={})
port is <lava.magma.core.process.ports.ports.OutPort object at 0x7f22a7f1a460>
and initializers_lookup is PortInitializer(name='s_out', shape=(1, 1),
d_type=<class 'numpy.int32'>, port_type='OutPort', size=64, transform_funcs={})

**Comment by mathisrichter** [comment]
The isse has since been resolved. The problem is in line
```python
dataloader.s_out = dataloader.s_out.flatten()
```
as `.flatten()` creates a virtual port, which here overwrote the original OutPort `s_out` of the `dataloader` Process.
