### ISSUE TITLE
Unit tests break with numpy version 1.24

### ISSUE THREAD

**Issue by tim-shea** [lava-nc/lava#568]
Objective of issue:
Convert all uses of numpy.int or numpy.float to bare int or float to fix unit tests.

**Lava DL version:**
- [x] **0.2.1** (bug fixes)

**I'm submitting a ...** 
- [x] bug report

**Current behavior:**
- With numpy 1.24, 5 unit tests fail with "AttributeError: module 'numpy' has no attribute 'int'" due to use of deprecated numpy.int alias.

**Expected behavior:**
- All unit tests should pass with the latest numpy.

**Comment by bamsumit** [comment]
This seems to stem from implementation in lava. I have transferred the issue there.
