### ISSUE TITLE
Move validation of equivalence of ports and vars of Proc and ProcModel from Builder into Compiler

### ISSUE THREAD

**Issue by awintel** [lava-nc/lava#57]
Right now, the currently only available PyProcBuilder validates that the Vars and Ports defined in a Proc have a corresponding Var and Port implementation in a ProcModel.

Since this will also be required for other types of ProcModels in the future, we should pull this out of the builder and put it into the compiler directly and call it as early as possible once a ProcModel has been selected for a Proc.

**Comment by tim-shea** [comment]
Not sure if this is still the case, but clearly it's not a major blocker for anything.
