### ISSUE TITLE
Monitor process

### ISSUE THREAD

**Issue by PhilippPlank** [lava-nc/lava#573]
### User story

As a user I want to have the Monitor process available to monitor and record the state of one or multiple variables of processes across all available compute resources.

### Conditions of satisfaction
- Monitor process can be used to probe variables of processes executed on CPU and Loihi 2.
- Monitor process can monitor multiple variables of another process.
- Monitor process can monitor and record variables of processes executed on different compute resources.

### Acceptance tests
- Create a Monitor for a LIF-Dense-LIF process and probe current and voltage during execution on CPU and Loihi 2.
- Create a Monitor and probe variables on a process running on Loihi 2 and a variable for a process running on CPU (same network).

**Comment by mathisrichter** [comment]
What does "monitoring" mean? Is this about recording the values of Vars over the execution time of a Process and making that recording available to the user at the end of execution? In that case, I would call the Process `Recorder`. A "monitor" to me implies a live visualization.
Could we formulate this more precisely in the story?

**Comment by mathisrichter** [comment]
Should it also be possible to record from different compute resources simultaneously? I think yes.

**Comment by awintel** [comment]
Doesn't have to be for visualization:

Monitor:
noun
1.
an instrument or device used for observing, checking, or keeping a continuous record of a process or quantity.

**Comment by tim-shea** [comment]
We have most of this functionality enabled at this point, if there are remaining issues in the io.state.Read class or the Buffer class or the Extractor class, please submit issues more specific to those things.
