### ISSUE TITLE
Event-based input sources (vision) in Lava

### ISSUE THREAD

**Issue by gkarray** [lava-nc/lava#576]
### User story
As a user, I want to be able to feed event-based vision data coming from iniVation or Prophesee cameras, .aedat, .dat or .raw files to Lava Processes in order to build SNN algorithms harnessing event-based vision data.

Note: As a user, I would also potentially want to include several pre-processing steps to the pipeline.

### Conditions of satisfaction
- Users can feed data coming from an iniVation camera to a Lava Process.
- Users can feed (vision, 2D) data coming from a .aedat file to a Lava Process.
- Users can feed data coming from a Prophesee camera to a Lava Process.
- Users can feed (vision, 2D) data coming from a .raw file to a Lava Process.
- Users can feed (vision, 2D) data coming from a .dat file to a Lava Process.
- (Optional) Users can inclue pre-processing steps.

### Acceptance tests
- Lava interface to reading from an event-based INIvation camera is available.
- Lava interface to reading from an event-based video with the INIvation file format, .aedat, is available.
- Lava interface to reading from an event-based Prophesee camera is available.
- Lava interface to reading from an event-based video with the Prohesee file format, .dat, is available.
- Lava interface to reading from an event-based video with the Prohesee file format, .raw, is available.

### Stories
- [x] #577
- [x] #603

**Comment by tim-shea** [comment]
@gkarray @mathisrichter @weidel-p Can someone update the status of this issue? This is a high priority now and should probably correctly reflect the remaining needs/gaps.

**Comment by gkarray** [comment]
@tim-shea I am closing this issue as it is outdated and this repository is not the right place for it.

A new story has been created lava-peripherals: https://github.com/lava-nc/lava-peripherals/issues/38. 
It encompasses, among other things, the content of this issue.
