### ISSUE TITLE
Measure average power

### ISSUE THREAD

**Issue by briandersn** [lava-nc/lava#584]
### User story
As a user, I want to [capability] to [benefit].

### Conditions of satisfaction
- An optional list of conditions that have to be fulfilled for this feature to be complete.
- For example: "Users can add both individual items and lists as parameters."

### Acceptance tests
- An optional list of tests that should be written to automatically test the new feature.

**Comment by tim-shea** [comment]
@briandersn Closing as this appears to be incomplete, but please feel free to reopen if there's something useful here.
