### ISSUE TITLE
Interfaces with IO, DDS middleware (ROS) and other 3rd party software

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#596]
### User story
As a Lava user, I want to have interfaces with I/O entities (files, sensors), ROS's middleware implementation (DDS) and other 3rd party software to build complex applications Lava involving input and output.

### Conditions of satisfaction
- Users can read from frame-based input files (sequence of images, audio, video).
- Users can read from event-based input files (audio, video).
- Users can read from frame-based input files (RGB camera, microphone).
- Users can read from event-based input files (cochlea, retina).
- Users can read from/write to .npy files.
- Users can subscribe/publish to ROS topics from Lava.
- Users can receive data from/send data to outside Lava.

### Acceptance tests
- Lava interface to reading from a sequence of frame-based image files is available (.png, .jpg, ...?).
- Lava interface to reading from frame-based audio files is available (.mp3, .wav, ...?).
- Lava interface to reading from frame-based video files is available (.mov, .avi, .mp4, .gif, ...?).
- Lava interface to reading from event-based audio files is available (INIvation format, aedat, Prophesee formats, raw, dat).
- Lava interface to reading from event-based video files is available (INIvation format, aedat).
- Lava interface to reading from frame-based microphone is available.
- Lava interface to reading from frame-based camera is available.
- Lava interface to reading from event-based cochlea is available (INIvation cochlea).
- Lava interface to reading from event-based camera is available (INIvation camera, Prophesee camera).
- Lava interface to reading from a .npy file is available.
- Lava interface to writing to a .npy file is available.
- Lava interface to subscribing to a ROS topic is available.
- Lava interface to publishing to a ROS topic is available.
- Lava interface to receiving data from outside Lava is available.
- Lava interface to sending data to outside Lava is available.

### Stories
- [x] #577
- [x] #576
- [x] #603

**Comment by tim-shea** [comment]
@mathisrichter @gkarray What is the status of this issue?

**Comment by gkarray** [comment]
@tim-shea This story is supposed to be an EPIC encompassing various IO interfaces we were envisioning integrating in Lava.

The ones related to input sources are still very relevant (although some more than other). 
The one related to .npy files is nice to have, but not prioritary.
The one related to ROS is still very relevant as well. It was supposed to build on the new C++ lava backend. However, as this might never happen, we have to find other ways to do it. Some initial promising ideas have already been explored by community members.
The one related to "outside lava" has been handled by the Injector and Extractor. 

As these pertain more to lava-peripherals, I am closing this issue and opening relevant ones in lava-peripherals.
