### ISSUE TITLE
Make Runtime a Python Context Manager

### ISSUE THREAD

**Issue by Gavinator98** [lava-nc/lava#599]
### User story
As a user, I want the Lava runtime to utilize [Python context managers](https://docs.python.org/3/reference/datamodel.html#context-managers) so it is easier to automatically call stop().

The proposed pattern of a runtime would be:
```python
with process_to_run:
    process_to_run.run(condition=RunSteps(num_steps=1000), run_cfg=run_config)
```

If there is interest in this design, I would be happy to implement it.

### Conditions of satisfaction
- A Python context manager can be used to automatically stop runtime.
- [other use cases?]
- Feature is fully unit tested for every use case.
- Public interface of the feature is documented with docstrings, where appropriate.
- Lava coding conventions are met.

**Comment by mathisrichter** [comment]
Hi @Gavinator98 

That is a great idea, thanks for proposing it and volunteering to work on it. We are very happy to support you in developing this nice feature.

Feel free to implement it and open a PR, linking back to this issue. We will review the PR and possibly suggest changes.

Before you start, please have a look at our [Lava developer guide](https://lava-nc.org/developer_guide.html), in particular the section on [Coding Conventions](https://lava-nc.org/developer_guide.html#coding-conventions). The first section of the guide is somewhat outdated but the coding conventions are still up-to-date.

For the PR, there need to be unit tests for all use cases of this feature as well as documentation in terms of docstrings, where appropriate.

We can use the comment section here to communicate if there are questions.
Please do not hesitate to reach out for clarification or help!

Mathis
