### ISSUE TITLE
Validator for ProcessModels

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#638]
### User story

As a user, I want to automatically validate the correctness of one ProcessModel of a Process against another ProcessModel of the same Process.

Notes: For instance, an application might use processes having both PyProcessModels
and NcProcessModels. In order to ensure that the Python SW model of a
NeuroCore produces the same result, this tool can be used to compare both
implementations. In doing so, it will point out exactly at which point in
time in which state variable a divergence in the internal dynamics occurs in
order to ease mismatch resolution.

**Comment by tim-shea** [comment]
@mathisrichter This is a neat idea, but doesn't seem feasible or narrow enough in scope to work on, and isn't a blocker for anything. Model developers can and should write manual validation.
