### ISSUE TITLE
GitHub LFS is not installed via poetry on MacOS

### ISSUE THREAD

**Issue by nicoliKim** [lava-nc/lava#664]
**git lfs is not installed via poetry**

When cloning the repository and installing from source following the guidelines provided in the main page of the Lava framework `git lfs` is not installed along with the Lava package. 

**Issue is detected when running lava tutorials**
1. When executing the tutorial at `lava/tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb` in order to avoid the ``UnpicklingError`` when instantiating the ``ImageClassifier`` I followed the instruction to download the pertained weights as in the notebook and ran
```bash
   git lfs fetch
   git lfs pull
```
in the newly instantiated environment.

2. It turns out that ``git lfs``  did not seem to be installed and I had to install it myself. While this is not a big deal, it may be worth including this dependency such that it gets installed via poetry. 

**Environment:**
 - Device: MacBook Pro 2022 16"
 - OS: MacOS Ventura Version 13.2.1
 - Lava version: 0.6.0
 - Python Version: 3.10

**Comment by nicoliKim** [comment]
@mgkwill I cannot assign you to this directly for some reason.

**Comment by PhilippPlank** [comment]
@mgkwill I agree that adding it to poetry seems to be a good solution, is there anything speaking against it?

**Comment by mgkwill** [comment]
Git LFS is not a python dependency and thus cannot routinely be installed
by poetry.

Last I checked it needed to be installed as an OS package. If instructions
to install or a link are not in docs it should be added. Or if others have
workable ideas.

**Comment by mgkwill** [comment]
Closing as not doable with current tool-chain.
