### ISSUE TITLE
AttributeError in end-to-end tutorials 

### ISSUE THREAD

**Issue by nicoliKim** [lava-nc/lava#665]
**Recurrent ``AttributeError`` in end-to-end lava tutorials**

When running the tutorials at ``lava/tutorials/end_to_end/`` the execution fails throwing an ``AttributeError`` when using classes defined within the notebook. I suspect this may be related to multiprocessing on Python 3.10

**Reproducing the behaviour**
Executing ``lava/tutorials/end_to_end/tutorial01_mnist_digit_classification.ipynb`` in cell `[9]`:
1. I get the following output
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kimnicoli/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/kimnicoli/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'PySpikeInputModel' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/kimnicoli/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/kimnicoli/miniconda3/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'PyOutputProcessModel' on <module '__main__' (built-in)>
```
Same applies to other cells in other tutorials, e.g. `tutorial02_excitatory_inhibitory_network.ipynb`, where classes defined within the script are called. 

**Expected behavior**
I would expected the notebook to smoothly run through.

**Screenshots**
I attach a screenshot for completness
<img width="846" alt="Screenshot 2023-04-12 at 11 12 33" src="https://user-images.githubusercontent.com/36715366/231411471-5f94962a-16b5-41f0-b385-11c06f6a0d12.png">

**Environment (please complete the following information):**
 - Device: MacBook Pro 16"
 - OS: MacOS Ventura 13.2.1
 - Lava version: 0.6.0
 - Python version: 3.10

**Comment by nicoliKim** [comment]
@joyeshmishra I cannot assign you to this issue directly for some reason.

**Comment by PhilippPlank** [comment]
Please use this issue for similar problems: #247

This is related to combability problems with Mac OS/Windows and the multiprocessing library. For details please refer to the linked issue. Sorry for the late response and the inconvenience, we are trying to fix this for a long time now, but there is no straight forward solution, as long as we use the multiprocessing library.
