### ISSUE TITLE
Monitor Process: Monitoring Vars and OutPorts of processes

### ISSUE THREAD

**Issue by elvinhajizada** [lava-nc/lava#74]
A preliminary version of Monitor process should be implemented to monitor/probe internal states and outputs (OutPorts) of other processes during runtime. The collected data should be available to the user afterwards. In the preliminary version a Monitor process should be able to monitor at least single variable of a process.

**Comment by awintel** [comment]
Probably best to gather all requirements we have here. A single Variable per process is only of very limited use.

**Comment by elvinhajizada** [comment]
Once we decide what changes we need to make to enable multi-probing I can add those requirements also here and  close the other issue about disabling LavaPyType checks

**Comment by awintel** [comment]
I thinks it should be the other way around: First one comes up with the requirements for something you want to build, then you figure out how you do it.
