### ISSUE TITLE
Multi-var monitoring for PyProcModels

### ISSUE THREAD

**Issue by elvinhajizada** [lava-nc/lava#75]
### User story
As a user, I would like to monitor more than one variable with each `Monitor` Process. This would make code for process monitoring much more concise.

### Conditions of satisfaction
- A single Monitor process can be used to probe multiple Vars and/or OutPorts of several other processes.
- The test coverage of the newly added module is >95%.
- The code has been reviewed and is merged into `main`.

### Acceptance tests
- Test that single Monitor process can probe multiple Vars and/or OutPorts
- Test that the collected data is as expected in these multi-var monitoring settings
- Test that this is faster than creating one Monitor per var

### Fore reference, some additional info about the original issue that hindered multi-var probing

> Monitoring multiple Vars requires disabling checks for coherence between Process and ProcessModels
> 
> Dynamically adding new probes to a Monitor process (i.e. creating new `RefPort`and `InPorts`in the Monitor process) requires disabling checks for existence of corresponding `LavaPyType`for each newly created `RefPorts/InPorts`. More specifically the following lines in the `compiler.py` checks for this coherence between Process and ProcessModels:
> ```
> 
> b.set_variables(v)
> 
> self._get_port_dtype(pt, pm)
> 
> self._map_var_port_class(pt, proc_groups))
> ```

### Note 
There is a year-old pull request (#238), that tried to enable this, however this never went through or reviewed, as it got deprioritized at the time.

**Comment by PhilippPlank** [comment]
Could we make the Monitor process a hierarchical process, which instantiates additional sub processes (each with 1 RefPort + storage Var) for each Var we want to probe?

**Comment by awintel** [comment]
I agree this would not require this somewhat (currently) ugly disabling of checks we want to have in other cases. But wouldn't it be unnecessarily inefficient to spin up a system process for each individual Var we would want to monitor?

As we already discussed in another issue. I was hoping we could pull out those Proc/ProcModel consistency checks out from the Builder, which only gets executed at runtime, and do this upfront in the compiler where it might be easier to bypass in case of such special processes. 

I thought the usage of RefPort/VarPort already motivated such a refactoring to do the LavaPyType validation earlier.

**Comment by PhilippPlank** [comment]
Well, the question is if we really want that. If people can add Vars and Ports dynamically it will lead to hardly understandable code which might be a nightmare to debug in the future.

Another idea would be to introduce a LavaType which represents a list and can be dynamically filled with a certain LavaType e.g. RefPorts. In this case it would be clear for the Process and ProcessModel that a there is a list, which might be filled dynamically and the ProcessModels needs to handle that.
