### ISSUE TITLE
If a process model is not decorated with `@tag`, then raise appropriate exception at run-time

### ISSUE THREAD

**Issue by srrisbud** [lava-nc/lava#79]
Currently, `@tag` decorator adds `ProcessModel.tags` attribute, which is used by appropriate `RunConfig`s. If a ProcessModel is not decorated with the decorator, then there is no tag attribute. This should be handled with grace by raising a verbose exception. Currently, we only get `<...> has no attribute tags`

**Comment by awintel** [comment]
The AbstractProcessModel class has default class variables for the other decorator fields. Why not do it the same way for tags? The do not have to be any tags. Seems like something optional a developer might do.
