### ISSUE TITLE
StateProbe doesn't work if there's no access to `/tmp`

### ISSUE THREAD

**Issue by jlubo** [lava-nc/lava#799]
I describe here an issue that I posted [on Confluence](https://intel-ncl.atlassian.net/wiki/spaces/NAP/pages/1785856001/Get+Started+with+Intel+Loihi+2) earlier today. It may be related to https://github.com/lava-nc/lava/issues/548.

Trying to run `tutorialX05_probing_states.ipynb` in vLab with lava-loihi v0.5.0, I’m getting a
```
PermissionError: [Errno 13] Permission denied: ‘/tmp/temp_state/var_id_1.npy'
```
I have temporarily fixed this by modifying line 30 in `lava_nx_env/lib/python3.8/site-packages/lava/utils/loihi2_state_probes.py` such that a local directory is used: 
```
root = os.path.join(os.getcwd(), "tmp/")
```
Anyway, the issue might wanna be addressed in the next version of lava-loihi.

**Comment by PhilippPlank** [comment]
Thanks for raising this issue. There should be a fix in the next release.
