### ISSUE TITLE
Incomplete PyPort hierarchy

### ISSUE THREAD

**Issue by awintel** [lava-nc/lava#84]
Currently, there is an 'unexpected argument' type warning in PyProcBuilder.build() at:
`port = port_cls(csp_ports, pm, p.shape, lt.d_type)`

This is because PyInPort, PyOutPort, ... have constructors like this:
`def __init__(self, csp_recv_ports: ty.List[CspRecvPort], *args):`
`    self._csp_recv_ports = csp_recv_ports`
`    super().__init__(*args)`

... calling the AbstractPortImplementation constructor with the following signature:
`def __init__(`
`    self,`
`    process_model: "AbstractProcessModel",  # noqa: F821`
`    shape: ty.Tuple[int, ...] = tuple(),`
`    d_type: type = int):`

While this works, it is not good style. The Builder only expects an AbstractPyPort which does not have its own overloaded __init__ method but inherits it from AbstractPortImplementation. Thus the Builder throws the 'unexpected argument' warning.
PyInPort and PyOutPort must have  common parent class with an __init__function signature that expects the csp_port passed to it by the Builder.
Then we can also get rid of just accepting an anonymous argument list like *args which is unnecessary.

On a related note: Why is there an AbstractCspSendPort in the type hierarchy between CspSendPort and AbstractCspPort?
- AbstractCspSendPort does nothing but define an abstract send method
- Are there other CspSendPorts inheriting from AbstractCspSendPort?
Same for CspOutPorts...

**Comment by PhilippPlank** [comment]
Add PR #131 to close this issue.

AbstractCspSendPort and AbstractCspRecvPort are not channel specific, while CspSendPort/CspRecvPort seems to be specifically implemented for pypy channels.
