### ISSUE TITLE
Neurons with firing adaptation

### ISSUE THREAD

**Issue by jlubo** [lava-nc/lava#845]
So far, neurons with firing adaptation have not yet been added to the Lava library (although according neurons have been implemented in Lava-DL, see the links below). But such neurons are needed for applications that require sophisticated neuron-intrinsic plasticity as well for realistic neuroscience models.

**Comment by jlubo** [comment]
One possible such model is given by a **Leaky Integrate-and-Fire neuron with adaptive threshold and adaptive refractoriness** (which I'd therefore call **ATRLIF neuron**). 

The dynamics of the model are described by the following formulation, originating from Lava-DL (see [here](https://github.com/lava-nc/lava-dl/blob/main/src/lava/lib/dl/slayer/neuron/alif.py) and [here](https://github.com/lava-nc/lava-dl/blob/main/tutorials/lava/lib/dl/slayer/neuron_dynamics/dynamics.ipynb)):

* _Current_: $i[t] = (1-\delta_i) \cdot i[t-1] + x[t]$

* _Voltage_: $v[t] = (1-\delta_v) \cdot v[t-1] + i[t] + \mathrm{bias}$

* _Threshold_: $\theta[t] = (1-\delta_{\theta})\,(\theta[t-1] - \theta_0) + \theta_0$

* _Refractory state_: $r[t] = (1-\delta_r)\,r[t-1]$

* _Spike event_: $s[t] = (x[t] - r[t]) \geq \theta[t]$

* _Refractory post-spike event_: $r[t] = r[t] + 2\,\theta[t]$

* _Threshold post-spike event_: $\theta[t] = \theta[t] + \theta_{\text{step}}$


With the following parameters (cf. 'atrlif_process.py'):

* $\delta_i$: Decay constant for current $i$.
    
* $\delta_v$: Decay constant for voltage $v$.
    
* $\delta_\theta$: Decay constant for threshold $\theta$.
    
* $\delta_r$: Decay constant for refractory state $r$.
    
* $\theta_0$: Initial/baseline value of threshold $\theta$.
    
* $\theta_\text{step}$: Increase of threshold theta upon the occurrence of a spike.
    
* $\mathrm{bias}$: Neuron's bias.

**Comment by PhilippPlank** [comment]
Thanks for adding this. I will take a look at the PR.
