### ISSUE TITLE
Example code not working

### ISSUE THREAD

**Issue by matham** [lava-nc/lava#90]
I'm following the first example code from the readme and I'm running into issues.

Here's the traces:

```py
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from lava.proc.dense.process import Dense
>>> from lava.proc.lif.process import LIF
>>>
>>> lif1 = LIF()
>>> dense = Dense()
>>> lif2 = LIF()
>>>
>>> # Connect processes via their directional input and output ports
>>> lif1.out_ports.s_out.connect(dense.in_ports.s_in)
>>> dense.out_ports.a_out.connect(lif2.in_ports.a_in)
>>> from lava.magma.core.run_conditions import RunSteps
>>> from lava.magma.core.run_configs import RunConfig
>>> lif1.run(condition=RunSteps(num_steps=10), run_cfg=SimpleRunConfig(sync_domains=[]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'SimpleRunConfig' is not defined
```

So then I change `SimpleRunConfig(sync_domains=[])` to `RunConfig()` and get the following:

```py
>>> lif1.run(condition=RunSteps(num_steps=10), run_cfg=RunConfig())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\Python\spnet\lava\src\lava\magma\core\process\process.py", line 394, in run
    executable = self.compile(run_cfg)
  File "G:\Python\spnet\lava\src\lava\magma\core\process\process.py", line 345, in compile
    return compiler.compile(self, run_cfg)
  File "G:\Python\spnet\lava\src\lava\magma\compiler\compiler.py", line 1010, in compile
    proc_map = self._map_proc_to_model(procs, run_cfg)
  File "G:\Python\spnet\lava\src\lava\magma\compiler\compiler.py", line 228, in _map_proc_to_model
    if issubclass(model_cls, AbstractSubProcessModel):
  File "C:\Users\Matthew Einhorn\AppData\Local\Programs\Python\Python310\lib\abc.py", line 123, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
```

A second issue, is that if I then try again the same command, I get this:
```py
>>> lif1.run(condition=RunSteps(num_steps=10), run_cfg=RunConfig())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\Python\spnet\lava\src\lava\magma\core\process\process.py", line 394, in run
    executable = self.compile(run_cfg)
  File "G:\Python\spnet\lava\src\lava\magma\core\process\process.py", line 345, in compile
    return compiler.compile(self, run_cfg)
  File "G:\Python\spnet\lava\src\lava\magma\compiler\compiler.py", line 1007, in compile
    raise ex.ProcessAlreadyCompiled(p)
lava.magma.compiler.exceptions.ProcessAlreadyCompiled: Process 'Process_0::LIF' has been compiled already. Processes can't be compiled more than once.
```

I don't know if that is intended, but it would be nice that I didn't have to create new objects so as not to run into the already compiled issue! Or, if there's a way to clear the compilation state, maybe include that as a suggestion in the error?

**Comment by mgkwill** [comment]
Hi @matham thanks for filing this issue! Also sorry about the bug. I've pushed an PR to fix the issue. 

I'd suggest you follow our tutorials however (see https://github.com/lava-nc/lava/tree/main/src/lava/tutorials/in_depth) , as they are more interesting and *fingers crossed* tested.

**Comment by mgkwill** [comment]
> A second issue, is that if I then try again the same command, I get this:
> 
> ```python
> >>> lif1.run(condition=RunSteps(num_steps=10), run_cfg=RunConfig())
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "G:\Python\spnet\lava\src\lava\magma\core\process\process.py", line 394, in run
>     executable = self.compile(run_cfg)
>   File "G:\Python\spnet\lava\src\lava\magma\core\process\process.py", line 345, in compile
>     return compiler.compile(self, run_cfg)
>   File "G:\Python\spnet\lava\src\lava\magma\compiler\compiler.py", line 1007, in compile
>     raise ex.ProcessAlreadyCompiled(p)
> lava.magma.compiler.exceptions.ProcessAlreadyCompiled: Process 'Process_0::LIF' has been compiled already. Processes can't be compiled more than once.
> ```
> 
> I don't know if that is intended, but it would be nice that I didn't have to create new objects so as not to run into the already compiled issue! Or, if there's a way to clear the compilation state, maybe include that as a suggestion in the error?

On the compilation issue I'll get back to you.

**Comment by awintel** [comment]
Just a note on the issues found here:
1. RunConfig() Is an abstract class and cannot be instantiated. The readme was just outdated. Thanks Marcus for fixing this.
2. Yes, it is intended that a Process cannot be compiled twice. But you should be able to run it twice. When you run it twice, Lava should recognize that the processes are already compiled and proceed directly to execution where you left of previously.
