### ISSUE TITLE
`set()` on `Var` does not block until value is actually updated

### ISSUE THREAD

**Issue by gkarray** [lava-nc/lava#97]
Currently in Lava, setting a `Var` with `set()` does not block until the value of the `Var` is actually changed. This can potentially lead to problems in cases where we may want to change the value of some `Var` between two consecutives runs with `RunSteps` condition.

Typical use case :

```python
process = Process()

process.run(condition=RunSteps(num_steps=1), run_cfg=Loihi1SimCfg())

process.some_var.set(some_value)

process.run(condition=RunSteps(num_steps=1), run_cfg=Loihi1SimCfg())

process.stop()
```

As a result, sometimes, the second call to `process.run()` will actually execute before the value of `some_var` gets updated to `some_value` in the `ProcessModel`.

Shouldn't the call to `set()` block until some kind of ACK for actually setting the value is returned to continue code execution ?

Notes : 

- Calling `time.sleep()` for 0.1 seconds or so, just after `process.some_var.set(some_value)`, gives enough time for the `Var` to be updated before next `process.run()` executes.
- Calling `process.some_var.get()`, just after `process.some_var.set(some_value)`, makes the `Var` update its value before next `process.run()` executes.
Not sure if it's the delay incurred by the `get()` that gives enough time for the `set()` to be effective or if there is something intrinsic to `get()` that makes it wait for all updates to happen before continuing.

**Comment by awintel** [comment]
No this should clearly not happen. Thanks for discovering that.

When the Runtime statemachine is in state PAUSED, then all SET/GET commands should be processed before the Runtime can transition to RUNNING.

However, once we support RunContinuous, then asynchronous SET/GET commands should be possible as well. In this case the behavior will become non-deterministic but that just has to be accepted by the user in this case. If not, then the user must manually go to PAUSED, call SET/GET and then resume running.

**Comment by gkarray** [comment]
Here's a minimal unit test demonstrating this problem :

```
import unittest

import numpy as np

from lava.magma.core.decorator import implements, requires, tag
from lava.magma.core.model.py.model import PyLoihiProcessModel
from lava.magma.core.model.py.type import LavaPyType
from lava.magma.core.process.process import AbstractProcess
from lava.magma.core.process.variable import Var
from lava.magma.core.resources import CPU
from lava.magma.core.run_configs import Loihi1SimCfg
from lava.magma.core.run_conditions import RunSteps
from lava.magma.core.sync.protocols.loihi_protocol import LoihiProtocol


class DemoProcess(AbstractProcess):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        nb_runs = kwargs.pop("nb_runs")

        self.changed = Var(shape=(1, ), init=np.array([True]))

        self.changed_history = Var(shape=(nb_runs, ), init=np.nan)


@implements(proc=DemoProcess, protocol=LoihiProtocol)
@requires(CPU)
@tag('floating_pt')
class DemoProcessModel(PyLoihiProcessModel):
    changed: np.ndarray = LavaPyType(np.ndarray, bool)

    changed_history: np.ndarray = LavaPyType(np.ndarray, bool)

    def run_spk(self):
        self.changed_history[self.current_ts - 1] = self.changed[0]

        self.changed[0] = False


class TestNonDeterminismUpdate(unittest.TestCase):
    def test_non_determinism_update(self):
        nb_runs = 10

        demo_process = DemoProcess(nb_runs=nb_runs)

        for i in range(nb_runs):
            demo_process.run(condition=RunSteps(num_steps=1),
                             run_cfg=Loihi1SimCfg())

            demo_process.changed.set(np.array([True]))

            # Uncomment this, test will pass
            # Comment this, test will probably fail
            demo_process.changed.get()

        changed_history = demo_process.changed_history.get()

        demo_process.stop()

        np.testing.assert_array_equal(np.ones((nb_runs, )), changed_history)


if __name__ == '__main__':
    unittest.main()
```

**Comment by awintel** [comment]
How should we handle this in the future? Just add such unittests to the code base but skip them as long as Lava does not actually support it? @mgkwill ?
